name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      #3 1. Check out your code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Node.js (choose your version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Frontend: install & build
      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm install @babel/plugin-proposal-private-property-in-object --save-dev
          $env:CI = 'false'
          npm run build
            
      # 4. Backend: install & test (or just install if you have no tests yet)
      - name: Install & Test Backend
        working-directory: backend
        run: |
          npm install --legacy-peer-deps
          npm install --save-dev jest jest-junit
          $env:CI = 'true'
          npm test

      - name: Upload Test Report (junit.xml)
        uses: actions/upload-artifact@v4
        with:
          name: jest-test-report
          path: backend/junit.xml

      - name: Publish Test Report to GitHub UI
        uses: dorny/test-reporter@v1
        with:
          name: Jest Unit Tests
          path: backend/junit.xml
          reporter: jest-junit
          fail-on-error: true

      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: backend/coverage/lcov-report/
